### ISSUE TITLE
alternative download

### ISSUE THREAD

**Issue by mjowe** [RobinJ1995/be.robinj.ubuntu#13]
Hi!

I don't use Google Play. Do you plan to offer your Launcher as a direct download or through f-droid? Would be awesome.

Have a great day!

**Comment by RobinJ1995** [comment]
Currently Ubuntu Launcher is still in Beta. As such it makes little sense to have it in a lot of separate app stores. I may do this at a later stage, but not right now.
I'd give you a download link, but I have no recent and stable build on my computer right now :)

**Comment by RobinJ1995** [comment]
Since Ubuntu Launcher got taken down from the Google Play Store, I quickly threw together a website for it.

You can download the latest version (currently 0.5.12) from there.

http://ubuntu.robinj.be/

**Comment by Poussinou** [comment]
@RobinJ1995 Would it be ok now to include this app in F-Droid, if it meets the inclusion criteria? :)

**Comment by Poussinou** [comment]
What are the problematic (proprietary) libraries, just for my interest? :)

Anyway, thanks for you response 👍

**Comment by deshant** [comment]
So ... this project still alive?

**Comment by RobinJ1995** [comment]
I'd say so, yes... https://github.com/RobinJ1995/DistroHopper/commits/master

**Comment by Poussinou** [comment]
I totally get what you mean, thanks for your attention 👍 

(Obviously, this is still alive^^)
