### ISSUE TITLE
close running apps

### ISSUE THREAD

**Issue by isaacrg** [RobinJ1995/be.robinj.ubuntu#14]
Please could an enhancement be added, such that the running apps panel can close apps via a menu, perhaps when someone presses an app icon for a second. This would be really useful.

**Comment by RobinJ1995** [comment]
I don't have any plans for this at the moment, and see little use for it (since Android has a dedicated button for such a menu). Maybe later, though.

**Comment by isaacrg** [comment]
@RobinJ1995 Android Lollipop does. Earlier versions only show recent apps, and when swiped away are not closed. This button is presently useless on android.

**Comment by RobinJ1995** [comment]
They are closed when you swipe them away unless they have something that prevents them from being closed. It's not a task killer. Killing apps and clearing them from the system's memory is up to Android.
