### ISSUE TITLE
The app needs a new name. Dear users: Please suggest ideas here.

### ISSUE THREAD

**Issue by unforgettableid** [RobinJ1995/be.robinj.ubuntu#16]
Per [this post](//plus.google.com/+RobinJacobs/posts/62d5b9YYED9), Ubuntu Launcher needs a new name.

Dear launcher users:  Please help to brainstorm some ideas for a new name for the launcher.

I think we should try to include the word "Launcher" in the name, as many launchers do, in order to make it obvious what the app does.

I prefer that we not use [CamelCase](http://en.wikipedia.org/wiki/CamelCase) for the launcher's new name unless there's a great need to do so.  Nowadays, it's more popular to spell Android app names with spaces between words instead of in CamelCase.  Michael Hartford theorizes in a blog entry of his that CamelCase naming is a trend which is now dying out.  Caleb Crain has pointed out in _The New York Times Magazine_ that CamelCase names are harder to read than plain English names with spaces between words.

Here are my ideas:

-  ~~Open Launcher~~
    -  Another Android launcher already uses this name.  Too bad.  It was a very good name.  The name alludes to both _open source_ and _opening apps_.
-  Iconic Launcher
-  Linus Launcher
    -  But this is hard to spell:  people may misspell it "Linux Launcher" and so not find it using a web search.
-  Launcher Plus
    -  Maybe this name is too close to the name of "Holo Launcher Plus" or [this launcher](https://code.google.com/p/android-launcher-plus/).
-  ~~Better Launcher~~
    -  Another Android launcher already uses this name.
-  Finer Launcher
-  ~~App Junkie~~
    -  This name is too close to the name of the Android developer "App Junkie Studio".
-  Infinite Launcher
    -  So chosen because the launcher's app list supports infinite scrolling.  (The stock AOSP launcher forces users to scroll page-by-page instead.)

Whatever name we pick, we should search the Web and the Google Play store to see whether or not the name has already been taken.

Please reply below and make your own suggestions.

P.S.  Dear readers:  I am not a Ubuntu Launcher developer, just a happy user of the launcher.

**Comment by RobinJ1995** [comment]
Thank you for taking the effort. Back when I made the original post on
Google+, someone suggested Distrohopper, which falls in line with what I
have planned for the project (a generic Linux-themed home screen
replacement which is not tied to a specific distribution, but has themes
available for several distributions; currently there are working Ubuntu and
Elementary OS themes).

Please do feel free to brainstorm for a bit, though, since I haven't
decided on anything yet. So far Distrohopper has simply been the best
suggestion I've seen :)

**Comment by unforgettableid** [comment]
No problem.

Distrohopper is okay, except:

1.  It's confining.  If someone will contribute a theme which isn't Linux-inspired &mdash; perhaps a nature-inspired or Windows-inspired theme &mdash; the name will be inaccurate.

2.  The name "Distrohopper" doesn't tell you that it's a launcher.  In fact, it sounds more like a tool meant to let you install Linux on your Android device, similar to GNURoot.  :)

You might want to choose a name which shows that the launcher is changeable.  "Chameleon Launcher" is already taken.

/me plays with powerthesaurus.org

You could use one of the following.

-  Fluid Launcher
    -  I like this name.  It implies changeability, plus it shows that the app list is a continuously-scrolling list, not paginated into discrete "pages".
-  Flowing Launcher
    -  Though maybe this name is too similar to the launcher named "Flow Home".
-  River Launcher
-  Sea Launcher

**Comment by unforgettableid** [comment]
On second thought, I think "DistroHopper" is a poor name, for the reasons I've already stated.

Here's a list of additional random name ideas which I've thought of.  I haven't filtered the list much in order to decide which ideas are good or bad.  And I haven't looked to see if any of these names are already taken by other launchers.

- Endless Launcher
- Taller Launcher
- Longer Launcher
- Mongo Launcher
- Mondo Launcher
- Lawn Chair Launcher
- Mobius Launcher
- Rhombus Launcher
- Thomas Launcher
- Somber Launcher
- InfiniLauncher
- Infinite Launcher
- Stauncher Launcher
- Stronger Launcher
- Loop Launcher
- Super Launcher
- Hyper Launcher
- Viper Launcher
- Nicer Launcher
- Ricer Launcher
- Finer Launcher
- Aero Launcher
- Glider Launcher
- Silver Launcher
- Wino Launcher
- Connor Launcher
- Iceberg Launcher
- Lean Launcher
- Slim Launcher
- Thin Launcher
- Wider Launcher
- Minor Launcher
- Tiger Launcher
- Ideal Launcher
- IdeaLauncher
- Real Launcher
- Surreal Launcher
- Speedy Launcher
- Light Launcher
- Luxe Launcher
- LinLauncher
- Lilo Launcher
- Cubic Launcher
- Micro Launcher
- Libre Launcher
- Libra Launcher
- Funner Launcher
- Stunner Launcher
- Tomato Launcher
- Color Launcher
- Kibo Launcher
- Sponsored Launcher
- Program Manager
- Android Executive
- Grand Prix Launcher
- Belgian Launcher
- Jacobs Launcher
- Stream Launcher
- App Launcher
- Software Launcher

Do any of these names appeal to you as much as "DistroHopper"?

**Comment by unforgettableid** [comment]
If not, please let me know, and perhaps I can think of some more ideas.

**Comment by RobinJ1995** [comment]
Thank you for your suggestions, they're much appreciated. However, I feel like DIstroHopper would be a more suitable name considering the changes I'm making to the app.
